### ISSUE TITLE
no binding on ngvas-image src property

### ISSUE THREAD

**Issue by romaincorral** [patrimart/ngvas#1]
Hi,
I want to use your ngvas angular2 module but it's seems the ngvas-image element don't bind the src value.
I want to change the ngvas-image src from another component.
The binding is available on other element like the fill attribut on ngvas-arc for example. 
Do you have a solution for that ?

**Comment by patrimart** [comment]
I will have a fix for this by the end of today. Shot in the dark: have you made sure it isn't a cross domain issue?

**Comment by patrimart** [comment]
It turns out that there's a small "bug" that requires `<ngvas-image>` to set the `fill` attribute to make it visible. For example...

`<ngvas-image fill="rgba(0,0,0,0)" [x]="10" [y]="10" [width]="100" [height]="100" src="../test/bird.jpg"></ngvas-image>`

I will implement a fix for the next release, but this workaround should get you going with no compatibility problems.

**Comment by romaincorral** [comment]
Thank you, 
It's OK with fill="rgba(0,0,0,0)"
